# Generated by Django 3.1.5 on 2021-05-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='updated',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
