# Generated by Django 3.1.5 on 2021-05-09 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
        ('SoftWord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image_attached', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Attach_picture')),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_info', to='Profile.profile')),
                ('comments', models.ManyToManyField(blank=True, default=None, related_name='myComments', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_info', to='SoftWord.domains')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='myLikes', to=settings.AUTH_USER_MODEL)),
                ('shares', models.ManyToManyField(blank=True, default=None, related_name='myShares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
